spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/gulimall_sms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        group: DEFAULT_GROUP
  application:
    name: gulimall-coupon

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 7000

management:
  endpoints:
    web:
      exposure:
        include: '*'